import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "tailwindcss";

import "./globals.css";
import Footer from "./Footer/page";
import Navbar from "./Navbar/page";
import {Store} from "./Redux/Store.js"
import StoreProvider from "./Redux/StoreProvider";
import { Toaster } from "react-hot-toast";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <StoreProvider  store={Store}>

    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Toaster/>

        {children}
       
        
        <Footer/>
        
        </body>
    </html>
    </StoreProvider>
  );
}
